apiVersion: v1
kind: ServiceAccount
metadata:
  name: amr-pipeline-sa
  namespace: ${NAMESPACE}
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::${ACCOUNT_ID}:role/amr-pipeline-s3-access"
