#!/bin/bash
# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0

set -euo pipefail

###########################
###### Default Values #####
###########################

RUN_SETUP=true
SETUP_ARGS=""
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
AWS_REGION=$(aws configure get region 2>/dev/null || echo "us-west-2")
SLURM_OPERATOR_VERSION="1.0.1"
SLURM_CHART_VERSION="1.0.1"
MARIADB_OPERATOR_VERSION="25.10.4"
CERT_MANAGER_VERSION="1.19.2"
LB_CONTROLLER_CHART_VERSION="1.11.0"
LB_CONTROLLER_POLICY_URL="https://raw.githubusercontent.com/kubernetes-sigs/aws-load-balancer-controller/v2.11.0/docs/install/iam_policy.json"
LB_CONTROLLER_IAM_ROLE_NAME="AmazonEKS_LB_Controller_Role_slinky"
LB_CONTROLLER_IAM_POLICY_NAME="AWSLoadBalancerControllerIAMPolicy_slinky"

###########################
###### Usage Function #####
###########################

usage() {
    cat <<EOF
Usage: $0 [OPTIONS]

Install the Slurm cluster on HyperPod EKS. Runs setup.sh first (unless
--skip-setup is specified), then deploys MariaDB, the Slurm operator, and
the Slurm cluster via Helm.

Optional:
  --skip-setup              Use previously generated slurm-values.yaml
  --region <region>         AWS region (default: AWS CLI configured or us-west-2)
  --help                    Show this help message

Options passed through to setup.sh:
  --node-type <g5|p5>       Instance profile
  --infra <cfn|tf>          Infrastructure method for CodeBuild stack
  --repo-name <name>        ECR repository name
  --tag <tag>               Image tag
  --local-build             Build image locally instead of CodeBuild
  --skip-build              Skip image build (use existing image in ECR)

Examples:
  # Full install: build image + deploy Slurm (g5 via CloudFormation)
  $0 --node-type g5 --infra cfn

  # Skip setup (slurm-values.yaml already generated)
  $0 --skip-setup

  # Build locally, then install
  $0 --node-type p5 --infra tf --local-build
EOF
    exit 0
}

###########################
###### Parse Arguments ####
###########################

while [[ $# -gt 0 ]]; do
    case $1 in
        --skip-setup)
            RUN_SETUP=false
            shift
            ;;
        --region)
            AWS_REGION="$2"
            SETUP_ARGS="${SETUP_ARGS} --region $2"
            shift 2
            ;;
        --help)
            usage
            ;;
        --node-type|--infra|--repo-name|--tag)
            SETUP_ARGS="${SETUP_ARGS} $1 $2"
            shift 2
            ;;
        --local-build|--skip-build)
            SETUP_ARGS="${SETUP_ARGS} $1"
            shift
            ;;
        *)
            echo "Error: Unknown option $1"
            echo "Run '$0 --help' for usage information."
            exit 1
            ;;
    esac
done

echo ""
echo "=========================================="
echo "  Slurm Cluster Installation"
echo "=========================================="
echo ""

###########################
## Run Setup ##############
###########################

if [[ "${RUN_SETUP}" == "true" ]]; then
    echo "Running setup.sh..."
    echo ""
    # shellcheck disable=SC2086
    bash "${SCRIPT_DIR}/setup.sh" ${SETUP_ARGS}
else
    echo "Skipping setup (--skip-setup)..."
    if [[ ! -f "${SCRIPT_DIR}/slurm-values.yaml" ]]; then
        echo "Error: slurm-values.yaml not found."
        echo "  Run without --skip-setup, or generate it manually."
        exit 1
    fi
    echo "  Using existing slurm-values.yaml"
fi

echo ""

###########################
## Source env_vars.sh #####
###########################

if [[ -f "${SCRIPT_DIR}/env_vars.sh" ]]; then
    source "${SCRIPT_DIR}/env_vars.sh"
fi

# EKS_CLUSTER_NAME and VPC_ID are needed for the LB Controller.
# They come from env_vars.sh (generated by deploy.sh).
if [[ -z "${EKS_CLUSTER_NAME:-}" ]]; then
    echo "Error: EKS_CLUSTER_NAME not set. Run deploy.sh first or set it in env_vars.sh."
    exit 1
fi
if [[ -z "${VPC_ID:-}" ]]; then
    echo "Error: VPC_ID not set. Run deploy.sh first or set it in env_vars.sh."
    exit 1
fi

AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)

###########################
## Install cert-manager ###
###########################

echo "Installing cert-manager (v${CERT_MANAGER_VERSION})..."

helm repo add jetstack https://charts.jetstack.io 2>/dev/null || true
helm repo update jetstack

if ! helm status cert-manager -n cert-manager &>/dev/null; then
    helm install cert-manager jetstack/cert-manager \
        --version="${CERT_MANAGER_VERSION}" \
        --namespace=cert-manager --create-namespace \
        --set crds.enabled=true \
        --wait
    echo "  cert-manager installed."
else
    echo "  cert-manager already installed."
fi

# Wait for cert-manager webhook to be ready (prevents race conditions
# with components that create Certificate resources at install time).
echo "  Waiting for cert-manager webhook..."
kubectl wait --for=condition=Available \
    deployment/cert-manager-webhook \
    -n cert-manager --timeout=120s
echo "  cert-manager webhook ready."

###########################
## Tag Public Subnets #####
###########################

# The AWS LB Controller requires public subnets to have the tag
# kubernetes.io/role/elb=1 for internet-facing NLBs. The HyperPod CFN
# template does NOT add this tag, so we add it here.
echo "Tagging public subnets for LB Controller (kubernetes.io/role/elb=1)..."

PUBLIC_SUBNET_IDS=$(aws ec2 describe-subnets \
    --filters "Name=vpc-id,Values=${VPC_ID}" \
              "Name=map-public-ip-on-launch,Values=true" \
    --query "Subnets[].SubnetId" --output text \
    --region "${AWS_REGION}" 2>/dev/null || echo "")

if [[ -n "${PUBLIC_SUBNET_IDS}" ]]; then
    for SUBNET_ID in ${PUBLIC_SUBNET_IDS}; do
        aws ec2 create-tags \
            --resources "${SUBNET_ID}" \
            --tags "Key=kubernetes.io/role/elb,Value=1" \
            --region "${AWS_REGION}"
        echo "  Tagged ${SUBNET_ID}"
    done
else
    echo "  WARNING: No public subnets found in VPC ${VPC_ID}."
    echo "  The LB Controller may not be able to provision internet-facing NLBs."
fi

###########################
## Install LB Controller ##
###########################

echo ""
echo "Installing AWS Load Balancer Controller (chart v${LB_CONTROLLER_CHART_VERSION})..."

helm repo add eks https://aws.github.io/eks-charts 2>/dev/null || true
helm repo update eks

# Create IAM policy for the LB Controller (idempotent -- ignores if exists)
if ! aws iam get-policy \
    --policy-arn "arn:aws:iam::${AWS_ACCOUNT_ID}:policy/${LB_CONTROLLER_IAM_POLICY_NAME}" \
    &>/dev/null; then
    echo "  Creating IAM policy ${LB_CONTROLLER_IAM_POLICY_NAME}..."
    POLICY_JSON=$(curl -fsSL "${LB_CONTROLLER_POLICY_URL}")
    LB_POLICY_ARN=$(aws iam create-policy \
        --policy-name "${LB_CONTROLLER_IAM_POLICY_NAME}" \
        --policy-document "${POLICY_JSON}" \
        --query "Policy.Arn" --output text)
    echo "  Policy created: ${LB_POLICY_ARN}"
else
    LB_POLICY_ARN="arn:aws:iam::${AWS_ACCOUNT_ID}:policy/${LB_CONTROLLER_IAM_POLICY_NAME}"
    echo "  IAM policy already exists: ${LB_POLICY_ARN}"
fi

# Create IAM role for Pod Identity
if ! aws iam get-role --role-name "${LB_CONTROLLER_IAM_ROLE_NAME}" &>/dev/null; then
    echo "  Creating IAM role ${LB_CONTROLLER_IAM_ROLE_NAME}..."
    TRUST_POLICY='{"Version":"2012-10-17","Statement":[{"Effect":"Allow","Principal":{"Service":"pods.eks.amazonaws.com"},"Action":["sts:AssumeRole","sts:TagSession"]}]}'
    aws iam create-role \
        --role-name "${LB_CONTROLLER_IAM_ROLE_NAME}" \
        --assume-role-policy-document "${TRUST_POLICY}" \
        --no-cli-pager
    aws iam attach-role-policy \
        --role-name "${LB_CONTROLLER_IAM_ROLE_NAME}" \
        --policy-arn "${LB_POLICY_ARN}"
    echo "  Role created and policy attached."
else
    echo "  IAM role already exists: ${LB_CONTROLLER_IAM_ROLE_NAME}"
fi

LB_ROLE_ARN="arn:aws:iam::${AWS_ACCOUNT_ID}:role/${LB_CONTROLLER_IAM_ROLE_NAME}"

# Create Pod Identity association (idempotent -- check first)
EXISTING_ASSOC=$(aws eks list-pod-identity-associations \
    --cluster-name "${EKS_CLUSTER_NAME}" \
    --namespace "kube-system" \
    --service-account "aws-load-balancer-controller" \
    --region "${AWS_REGION}" \
    --query "associations[0].associationId" --output text 2>/dev/null || echo "None")

if [[ "${EXISTING_ASSOC}" == "None" || -z "${EXISTING_ASSOC}" ]]; then
    echo "  Creating Pod Identity association..."
    aws eks create-pod-identity-association \
        --cluster-name "${EKS_CLUSTER_NAME}" \
        --namespace "kube-system" \
        --service-account "aws-load-balancer-controller" \
        --role-arn "${LB_ROLE_ARN}" \
        --region "${AWS_REGION}" \
        --no-cli-pager
    echo "  Pod Identity association created."
else
    echo "  Pod Identity association already exists: ${EXISTING_ASSOC}"
fi

# Install the Helm chart
if ! helm status aws-load-balancer-controller -n kube-system &>/dev/null; then
    helm install aws-load-balancer-controller \
        eks/aws-load-balancer-controller \
        --version="${LB_CONTROLLER_CHART_VERSION}" \
        --namespace=kube-system \
        --set clusterName="${EKS_CLUSTER_NAME}" \
        --set region="${AWS_REGION}" \
        --set vpcId="${VPC_ID}" \
        --wait
    echo "  AWS Load Balancer Controller installed."
else
    echo "  AWS Load Balancer Controller already installed."
fi

# Wait for the webhook to be ready (prevents race conditions with
# Service annotations that trigger LB provisioning).
echo "  Waiting for LB Controller webhook..."
kubectl wait --for=condition=Available \
    deployment/aws-load-balancer-controller \
    -n kube-system --timeout=120s
echo "  LB Controller webhook ready."

###########################
## Apply FSx PVC ##########
###########################

echo ""
echo "Applying FSx Lustre PV/PVC..."
kubectl create namespace slurm 2>/dev/null || true
kubectl apply -f "${SCRIPT_DIR}/lustre-pvc-slurm.yaml"
echo "  FSx PV/PVC applied."

###########################
## Install MariaDB ########
###########################

echo ""
echo "Installing MariaDB operator (v${MARIADB_OPERATOR_VERSION})..."

helm repo add mariadb-operator \
    https://mariadb-operator.github.io/mariadb-operator 2>/dev/null || true
helm repo update mariadb-operator

if ! helm status mariadb-operator -n mariadb &>/dev/null; then
    helm install mariadb-operator mariadb-operator/mariadb-operator \
        --version="${MARIADB_OPERATOR_VERSION}" \
        --namespace=mariadb --create-namespace \
        --set crds.enabled=true \
        --wait
    echo "  MariaDB operator installed."
else
    echo "  MariaDB operator already installed."
fi

echo ""
echo "Creating MariaDB instance..."

kubectl apply -f "${SCRIPT_DIR}/mariadb.yaml"
echo "  MariaDB instance applied."

# Wait for MariaDB to be ready
echo "  Waiting for MariaDB to be ready..."
kubectl wait --for=condition=Ready mariadb/mariadb \
    -n slurm --timeout=300s 2>/dev/null || \
    echo "  WARNING: MariaDB readiness check timed out. Proceeding anyway."

###########################
## Install Slurm Operator #
###########################

echo ""
echo "Installing Slurm Operator (v${SLURM_OPERATOR_VERSION})..."

# Delete stale CRDs only if they exist (upgrading from pre-1.0 Slinky)
if kubectl get crd clusters.slinky.slurm.net &>/dev/null; then
    echo "  Removing stale CRD: clusters.slinky.slurm.net"
    kubectl delete crd clusters.slinky.slurm.net
fi
if kubectl get crd nodesets.slinky.slurm.net &>/dev/null; then
    echo "  Removing stale CRD: nodesets.slinky.slurm.net"
    kubectl delete crd nodesets.slinky.slurm.net
fi

if ! helm status slurm-operator -n slinky &>/dev/null; then
    helm install slurm-operator \
        oci://ghcr.io/slinkyproject/charts/slurm-operator \
        --version="${SLURM_OPERATOR_VERSION}" \
        --namespace=slinky --create-namespace \
        --set crds.enabled=true \
        --wait
    echo "  Slurm operator installed."
else
    echo "  Slurm operator already installed."
fi

###########################
## Install Slurm Cluster ##
###########################

echo ""
echo "Installing Slurm Cluster (v${SLURM_CHART_VERSION})..."

if ! helm status slurm -n slurm &>/dev/null; then
    helm install slurm \
        oci://ghcr.io/slinkyproject/charts/slurm \
        --values="${SCRIPT_DIR}/slurm-values.yaml" \
        --version="${SLURM_CHART_VERSION}" \
        --namespace=slurm
    echo "  Slurm cluster installed."
else
    echo "  Slurm cluster already installed."
fi

###########################
## Configure NLB ##########
###########################

echo ""
echo "Configuring login service NLB..."

# Wait for the login service to exist
echo "  Waiting for slurm-login-slinky service..."
until kubectl get service slurm-login-slinky -n slurm &>/dev/null; do
    sleep 5
done
echo "  Service found."

# Get public IP for NLB source range restriction
IP_ADDRESS="$(curl -s https://checkip.amazonaws.com)"
echo "  Source IP: ${IP_ADDRESS}"

# Generate and apply service patch
sed "s|\${ip_address}|${IP_ADDRESS}|g" \
    "${SCRIPT_DIR}/slurm-login-service-patch.yaml.template" \
    > "${SCRIPT_DIR}/slurm-login-service-patch.yaml"

kubectl patch service slurm-login-slinky -n slurm \
    --patch-file "${SCRIPT_DIR}/slurm-login-service-patch.yaml"
echo "  Login service patched with NLB annotations."

###########################
## Wait for NLB ###########
###########################

echo ""
echo "Waiting for NLB endpoint..."

SLURM_LOGIN_HOSTNAME=""
for i in $(seq 1 60); do
    SLURM_LOGIN_HOSTNAME=$(kubectl get services -n slurm \
        -l app.kubernetes.io/instance=slurm,app.kubernetes.io/name=login \
        -o jsonpath="{.items[0].status.loadBalancer.ingress[0].hostname}" 2>/dev/null || true)

    if [[ -n "${SLURM_LOGIN_HOSTNAME}" ]]; then
        break
    fi
    sleep 5
done

echo ""
echo "=========================================="
echo "  Installation Complete"
echo "=========================================="
echo ""

if [[ -n "${SLURM_LOGIN_HOSTNAME}" ]]; then
    echo "  Login endpoint: ${SLURM_LOGIN_HOSTNAME}"
    echo ""
    echo "  SSH into the Slurm login node:"
    echo "    ssh -i ~/.ssh/id_ed25519_slurm root@${SLURM_LOGIN_HOSTNAME}"
else
    echo "  WARNING: NLB hostname not yet available."
    echo "  Check with: kubectl get svc slurm-login-slinky -n slurm"
fi

echo ""
echo "  Verify cluster status:"
echo "    kubectl -n slurm get pods -l app.kubernetes.io/instance=slurm"
echo ""
